In [2]:
import numpy as np
x = [1,2,3,4,5]
x_np = np.array(x)

In [3]:
x

[1, 2, 3, 4, 5]

In [4]:
x_np

array([1, 2, 3, 4, 5])

In [5]:
type(x[0])

int

In [6]:
x_np.dtype

dtype('int32')

In [7]:
x = tuple(range(1,8))
x_np = np.arange(1,8)
x_np_1 = np.array(x)

In [8]:
x

(1, 2, 3, 4, 5, 6, 7)

In [9]:
x_np

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
x_np_1

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
arr = np.linspace(2.0,3.0,num = 5)
arr

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [24]:
arr = np.linspace(2,3,num= 5, endpoint = False)
arr

array([2. , 2.2, 2.4, 2.6, 2.8])

In [20]:
arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
arr = arr.reshape(-1)
arr

array([0., 0., 0., 0., 0., 0.])

In [25]:
arr = arr.reshape(-1,1)
arr

array([[2. ],
       [2.2],
       [2.4],
       [2.6],
       [2.8]])

In [27]:
arr = arr.reshape(3,-1)
arr

ValueError: cannot reshape array of size 5 into shape (3,newaxis)

In [29]:
arr = np.arange(1,25).reshape(2,3,4)
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])