In [1]:
import pandas as pd
import numpy as np
#숙제
df22 = pd.DataFrame(np.arange(0,100).reshape(20,5))
print(df22)
df22.quantile([0.25,0.55,0.75])

     0   1   2   3   4
0    0   1   2   3   4
1    5   6   7   8   9
2   10  11  12  13  14
3   15  16  17  18  19
4   20  21  22  23  24
5   25  26  27  28  29
6   30  31  32  33  34
7   35  36  37  38  39
8   40  41  42  43  44
9   45  46  47  48  49
10  50  51  52  53  54
11  55  56  57  58  59
12  60  61  62  63  64
13  65  66  67  68  69
14  70  71  72  73  74
15  75  76  77  78  79
16  80  81  82  83  84
17  85  86  87  88  89
18  90  91  92  93  94
19  95  96  97  98  99


0      1      2      3      4
0.25  23.75  24.75  25.75  26.75  27.75
0.55  52.25  53.25  54.25  55.25  56.25
0.75  71.25  72.25  73.25  74.25  75.25

In [129]:
np22 = np.arange(0,100).reshape(20,5)
print(np22)
np.quantile(np22[:0],[0.25,0.55,0.75])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]


IndexError: cannot do a non-empty take from an empty axes.

In [120]:
# df1 = pd.DataFrame(np.random.randn(5,4),columns=list("ABCD"),
#                    index=pd.date_range("2019701", periods = 5))
# df1

In [2]:
ser = pd.Series(np.random.randn(4),index=list("ABCD"))
ser

A    0.218964
B   -0.661874
C    0.037709
D   -0.754111
dtype: float64

In [3]:
ser.loc["B"]

-0.6618742299328652

In [4]:
ser.loc["C"] = 0

In [5]:
ser

A    0.218964
B   -0.661874
C    0.000000
D   -0.754111
dtype: float64

In [6]:
df1 = pd.DataFrame(np.random.randn(5,4),index = list('abcde'),columns=list("ABCD"))

In [7]:
df1

A         B         C         D
a  0.312138  0.398205 -1.715773  0.742825
b  0.132292  0.736925 -0.648600 -0.375587
c -0.987399 -1.422159  2.238116 -0.865397
d -1.104239  0.643629  2.224233  0.894040
e  0.070616 -1.003605  1.395476 -0.539329

In [8]:
df1.loc[['a','b','d'],:]

A         B         C         D
a  0.312138  0.398205 -1.715773  0.742825
b  0.132292  0.736925 -0.648600 -0.375587
d -1.104239  0.643629  2.224233  0.894040

In [30]:
df1.loc[['a','b','d'],"B":"D"]

B         C         D
a -0.125430  1.433003 -1.412814
b -0.313201  1.760704 -0.008470
d -0.257455  0.562016 -0.037979

In [11]:
#df1.iloc[['a','b','c']]

In [31]:
df1.loc[['a','b','d'],["B","D"]]

B         D
a -0.125430 -1.412814
b -0.313201 -0.008470
d -0.257455 -0.037979

In [45]:
#인덱스가 존재
ser1 = pd.Series(list("abcde"),index=[0,3,2,5,4])
ser1

0    a
3    b
2    c
5    d
4    e
dtype: object

In [46]:
ser1.loc[:2]

0    a
3    b
2    c
dtype: object

In [47]:
ser1[:2]

0    a
3    b
dtype: object

In [48]:
#인엑스가 없는 것
ser = pd.Series(list("abcde"))

In [49]:
ser.loc[:2]

0    a
1    b
2    c
dtype: object

In [52]:
ser2 = ser1.sort_index()
ser2

0    a
2    c
3    b
4    e
5    d
dtype: object

In [53]:
ser3 = ser1.sort_values()
ser3

0    a
3    b
2    c
5    d
4    e
dtype: object

In [54]:
ser3.loc[0:3]

0    a
3    b
dtype: object

In [55]:
ser3.iloc[0:3]

0    a
3    b
2    c
dtype: object

In [65]:
# df1 = pd.DataFrame(np.random.randn(5,4),index=list(range(0,10,2)),
#                    columns=list(range(0,8,2)))
df1 = pd.DataFrame(np.random.randn(5,4),index=list("abcde"),
                   columns=list("ABCD"))
df1

A         B         C         D
a -0.379223 -0.246741 -1.706873 -0.592889
b -1.016220  1.060121 -1.431638  0.384186
c  2.004496 -0.603209 -1.109410  0.809150
d -0.079290 -0.063572 -0.432455  1.882199
e -0.214524 -1.667271 -0.059055 -0.482732

In [66]:
df1.iloc[:2]

A         B         C         D
a -0.379223 -0.246741 -1.706873 -0.592889
b -1.016220  1.060121 -1.431638  0.384186

In [67]:
df1.iloc[1:3,0:3]

A         B         C
b -1.016220  1.060121 -1.431638
c  2.004496 -0.603209 -1.109410

In [68]:
df1.loc[lambda df:df.A > 0]

A         B        C        D
c  2.004496 -0.603209 -1.10941  0.80915

In [69]:
df1.loc[:,lambda df:df.loc["a"]>0]

Empty DataFrame
Columns: []
Index: [a, b, c, d, e]

In [70]:
ser = pd.Series(np.arange(3))
ser

0    0
1    1
2    2
dtype: int32

In [74]:
df = pd.DataFrame(np.arange(9).reshape(3,3),columns=["A","B","C"])
data = ["A","W","E"]

In [76]:
#df.loc[:,"T"] = df.loc[:,"A"]
df.loc[:,"T"] = pd.Series(data)

In [77]:
df

A  B  C  T
0  0  1  2  A
1  3  4  5  W
2  6  7  8  E

In [78]:
data1 = [9,9,9,"s"]
df.loc[5, :] = data1
df

A    B    C  T
0  0.0  1.0  2.0  A
1  3.0  4.0  5.0  W
2  6.0  7.0  8.0  E
5  9.0  9.0  9.0  s

In [79]:
df.A

0    0.0
1    3.0
2    6.0
5    9.0
Name: A, dtype: float64

In [80]:
d1 = {'one':[1.0,2.0,3.0],"two":[4.0,5.0,6.0]}
df1 = pd.DataFrame(d1,index = ['a','b','c'])
df2 = df1.copy()

In [81]:
df2.loc['d'] = np.nan

In [82]:
df2["three"] = 2.0
df2.iloc[1:2,1:2] = np.nan

In [83]:
df1

one  two
a  1.0  4.0
b  2.0  5.0
c  3.0  6.0

In [85]:
df2

one  two  three
a  1.0  4.0    2.0
b  2.0  NaN    2.0
c  3.0  6.0    2.0
d  NaN  NaN    2.0

In [86]:
df12 = df1+df2

In [87]:
df12

one  three   two
a  2.0    NaN   8.0
b  4.0    NaN   NaN
c  6.0    NaN  12.0
d  NaN    NaN   NaN

In [88]:
df12.sum()

one      12.0
three     0.0
two      20.0
dtype: float64

In [89]:
df12.prod()

one      48.0
three     1.0
two      96.0
dtype: float64

In [90]:
df12.mean()

one       4.0
three     NaN
two      10.0
dtype: float64

In [91]:
df12.std()

one      2.000000
three         NaN
two      2.828427
dtype: float64

In [92]:
df12.max()

one       6.0
three     NaN
two      12.0
dtype: float64

In [93]:
df12.min()

one      2.0
three    NaN
two      8.0
dtype: float64

In [94]:
df12["one"].sum()

12.0

In [95]:
df12["one"].mean()

4.0

In [96]:
arr = np.array(np.arange(0,9).reshape(3,3))

In [97]:
print(arr)
print(arr[:,0].sum())
print(arr[:,0].mean())
print(arr[:,0].prod())
print(arr[:,0].std())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
9
3.0
0
2.449489742783178


In [98]:
df12.fillna(0)

one  three   two
a  2.0    0.0   8.0
b  4.0    0.0   0.0
c  6.0    0.0  12.0
d  0.0    0.0   0.0

In [100]:
data = {'name': ['haena', 'naeun', 'una', 'bum', 'suho'],
'age': [30, 27, 28, 23, 18],
'address': ['dogok', 'suwon', 'mapo', 'ilsan', 'yeoyi'],
'grade': ['A', 'B', 'C', 'B', 'A'],
'score': [100, 88, 73, 83, 95]}

df = pd.DataFrame(data, columns=['name', 'age', 'address', 'score', 'grade']) 
df

name  age address  score grade
0  haena   30   dogok    100     A
1  naeun   27   suwon     88     B
2    una   28    mapo     73     C
3    bum   23   ilsan     83     B
4   suho   18   yeoyi     95     A

In [101]:
#df.to_cvs("student_grade1.csv",sep="|")
#df1 = pd.read_csv("student_grade1.cvs",sep="|",index_col = 0)
#df1

In [102]:
dfj = pd.DataFrame([['a','b'],['c','d']],index=['row1','row2'],columns=['col1','col2'])
dfj.to_json()
dfj.to_json(orient='split')

'{"columns":["col1","col2"],"index":["row1","row2"],"data":[["a","b"],["c","d"]]}'

In [103]:
dfj.to_json(orient='records')

'[{"col1":"a","col2":"b"},{"col1":"c","col2":"d"}]'

In [104]:
dfj.to_json(orient='index')

'{"row1":{"col1":"a","col2":"b"},"row2":{"col1":"c","col2":"d"}}'

In [105]:
dfj.to_json(orient='columns')

'{"col1":{"row1":"a","row2":"c"},"col2":{"row1":"b","row2":"d"}}'

In [106]:
dfj.to_json(orient='values')

'[["a","b"],["c","d"]]'

In [107]:
dfj.to_json(orient='table')

'{"schema":{"fields":[{"name":"index","type":"string"},{"name":"col1","type":"string"},{"name":"col2","type":"string"}],"primaryKey":["index"],"pandas_version":"0.20.0"},"data":[{"index":"row1","col1":"a","col2":"b"},{"index":"row2","col1":"c","col2":"d"}]}'

In [108]:
df.to_json("happy_json.json")

In [109]:
dfj_r = pd.read_json("happy_json.json")

In [110]:
dfj_r

name  age address  score grade
0  haena   30   dogok    100     A
1  naeun   27   suwon     88     B
2    una   28    mapo     73     C
3    bum   23   ilsan     83     B
4   suho   18   yeoyi     95     A

In [12]:
url = 'http://www.fdic.gov/bank/individual/failed/banklist.html'
dfh = pd.read_html(url)
dfh
#lxml html5lib bs4 패키지 설치 필요..

ValueError: No tables found

In [112]:
!pip install lxml

In [113]:
!pip install beautifulsoup4

In [115]:
!pip install html5lib

In [118]:
df = pd.DataFrame(np.random.randn(2,2))
df

0         1
0 -0.154498  0.884221
1  0.024183 -0.795830

In [119]:
print(df.to_html())

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>0</th>
      <th>1</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>-0.154498</td>
      <td>0.884221</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0.024183</td>
      <td>-0.795830</td>
    </tr>
  </tbody>
</table>
