In [1]:
import pandas as pd
import numpy as np

In [2]:
data = np.random.random(4)
data

array([0.36702285, 0.82211182, 0.09977778, 0.14328159])

In [3]:
index = ['1','2','3','4']
ser = pd.Series(data,index = index)
ser

1    0.367023
2    0.822112
3    0.099778
4    0.143282
dtype: float64

In [29]:
dic = {"kimbap":"5000","Sundae":"4000"}
ser2 = pd.Series(dic)
ser2

kimbap    5000
Sundae    4000
dtype: object

In [30]:
ser2 = pd.Series(dic,index = ["a","kimbap","Sundae","d"])
ser2

a          NaN
kimbap    5000
Sundae    4000
d          NaN
dtype: object

In [31]:
ser2 = pd.Series(dic,index = ["a","Sundae","kimbap","d"])
ser2

a          NaN
Sundae    4000
kimbap    5000
d          NaN
dtype: object

In [32]:
ser3 = pd.Series(42,index = ["Answer","of","the","Universe"])
ser3

Answer      42
of          42
the         42
Universe    42
dtype: int64

In [33]:
ser3[0]

42

In [34]:
ser2["Sundae"]

'4000'

In [35]:
ser3["of"]

42

In [4]:
ser[:4]

1    0.367023
2    0.822112
3    0.099778
4    0.143282
dtype: float64

In [9]:
ser[::2]
print(np.exp(ser[0]))

1.44343089490096


In [7]:
np.exp(ser[::2])

1    1.443431
3    1.104925
dtype: float64

In [39]:
np.log(ser[::2])

1   -2.547634
3   -2.476013
dtype: float64

In [40]:
ser + ser2

1         NaN
2         NaN
3         NaN
4         NaN
Sundae    NaN
a         NaN
d         NaN
kimbap    NaN
dtype: object

In [42]:
ser4 = pd.Series(np.random.random(4))
ser5 = pd.Series(np.random.random(4))
print(ser4.values)
print(ser5.values)

[0.68040505 0.74776497 0.8367007  0.60031886]
[0.3467713  0.87926324 0.60988523 0.45326074]


In [43]:
ser4+ser5

0    1.027176
1    1.627028
2    1.446586
3    1.053580
dtype: float64

In [44]:
ser4[0]+ser5[0]

1.0271763498555029

In [47]:
ser4 = pd.Series(np.random.random(10))
ser5 = pd.Series(np.random.random(4))
ser4[:4]+ser5

0    0.419075
1    1.682630
2    1.475552
3    0.816968
dtype: float64

In [46]:
ser4_1 = ser4[:4]
ser4_1+ser5

0    0.832387
1    1.507405
2    0.380078
3    0.926881
dtype: float64

In [48]:
ser6 = pd.Series(data, name="abcd")
ser6

0    0.078267
1    0.546911
2    0.084078
3    0.493391
Name: abcd, dtype: float64

In [49]:
ser6_1 = ser6.rename("dcba")
ser6_1

0    0.078267
1    0.546911
2    0.084078
3    0.493391
Name: dcba, dtype: float64

In [50]:
ser6_1.name

'dcba'

In [52]:
d = {"하나":pd.Series([0,1,2],index = ["a","b","c"]),"둘":pd.Series([0,1,2,3],index=["a","b","c","d"])}
df = pd.DataFrame(d)
df

하나  둘
a  0.0  0
b  1.0  1
c  2.0  2
d  NaN  3

In [53]:
df = pd.DataFrame(d, index = ["b","c","a"],columns=["영","둘"])
df

영  둘
b  NaN  1
c  NaN  2
a  NaN  0

In [54]:
df.index

Index(['b', 'c', 'a'], dtype='object')

In [55]:
df.columns

Index(['영', '둘'], dtype='object')

In [56]:
arr = np.zeros((2,),dtype =[('A','i4'),('B','f4'),('C','a10')])
arr[:] = [(1,2,"Hello"),(2,3,"World")]
df = pd.DataFrame(arr)
df1 = pd.DataFrame(arr,index=['first','second'])
df2 = pd.DataFrame(arr,columns=['C','A','B'])
print(df)
print(df1)
print(df2)

   A    B         C
0  1  2.0  b'Hello'
1  2  3.0  b'World'
        A    B         C
first   1  2.0  b'Hello'
second  2  3.0  b'World'
          C  A    B
0  b'Hello'  1  2.0
1  b'World'  2  3.0


In [68]:
df = pd.DataFrame.from_dict(dict([('A',[1,2,3]),('B',[4,5,6])]),
                           orient = "index", columns = ["one","two","three"])
df

one  two  three
A    1    2      3
B    4    5      6

In [69]:
del df["one"]
df["random"] = "hello"
df

two  three random
A    2      3  hello
B    5      6  hello

In [74]:
data_dict = dict([('A',[1,2,3]),('B',[4,5,6])])
df_o = pd.DataFrame(data_dict)
df = pd.DataFrame.from_dict(data_dict, orient = "index", columns = ["one","two","three"])
df

one  two  three
A    1    2      3
B    4    5      6

In [75]:
df_o

A  B
0  1  4
1  2  5
2  3  6

In [76]:
df.insert(0,"whatup",df["three"])
df

whatup  one  two  three
A       3    1    2      3
B       6    4    5      6

In [77]:
ser = pd.Series([1,2,3],index = ['a','b','v'])
ser.drop(labels=["b"])

a    1
v    3
dtype: int64

In [80]:
df.drop(["whatup"],axis = 1)

one  two  three
A    1    2      3
B    4    5      6

In [81]:
df1= pd.DataFrame(np.arange(0,20).reshape(5,4), columns=['A','B','C','D'])
df2= pd.DataFrame(np.ones(9).reshape(3,3), columns=['A','B','C'])

In [82]:
df1

A   B   C   D
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [83]:
df2

A    B    C
0  1.0  1.0  1.0
1  1.0  1.0  1.0
2  1.0  1.0  1.0

In [84]:
df1+df2

A     B     C   D
0  1.0   2.0   3.0 NaN
1  5.0   6.0   7.0 NaN
2  9.0  10.0  11.0 NaN
3  NaN   NaN   NaN NaN
4  NaN   NaN   NaN NaN

In [85]:
ser = pd.Series(np.random.randn(1000))
ser.head()

0    0.337675
1    0.121355
2   -1.051075
3   -1.712219
4    0.061078
dtype: float64

In [86]:
ser.tail()

995   -1.565686
996    0.598979
997    0.424222
998    1.290102
999   -0.440541
dtype: float64

In [88]:
ind = pd.date_range('1/1/2022',periods = 5)
df = pd.DataFrame(np.random.randn(5,3), index = ind,columns=['A','B','C'])
df

A         B         C
2022-01-01 -0.285579 -1.203086 -0.349992
2022-01-02 -2.121628 -1.857178 -0.876443
2022-01-03  1.132989 -1.039624  0.824705
2022-01-04 -2.223438  1.375879  0.702373
2022-01-05 -0.935167  0.987990 -0.514166

In [89]:
df_2 = pd.DataFrame(np.ones(9).reshape(3,3),columns = ['A','B','C'])
df2

A    B    C
0  1.0  1.0  1.0
1  1.0  1.0  1.0
2  1.0  1.0  1.0

In [90]:
df_2*3+2

A    B    C
0  5.0  5.0  5.0
1  5.0  5.0  5.0
2  5.0  5.0  5.0

In [91]:
df1= pd.DataFrame(np.arange(0,20).reshape(5,4), columns=['A','B','C','D'])
df1.add(df2)

A     B     C   D
0  1.0   2.0   3.0 NaN
1  5.0   6.0   7.0 NaN
2  9.0  10.0  11.0 NaN
3  NaN   NaN   NaN NaN
4  NaN   NaN   NaN NaN

In [92]:
df = pd.DataFrame(np.arange(0,12).reshape(4,3))
df

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [94]:
df.mean(0)

0    4.5
1    5.5
2    6.5
dtype: float64

In [95]:
df.mean(1)

0     1.0
1     4.0
2     7.0
3    10.0
dtype: float64

In [96]:
df.sum(0)

0    18
1    22
2    26
dtype: int64

In [97]:
df.sum(1)

0     3
1    12
2    21
3    30
dtype: int64

In [98]:
df.std()

0    3.872983
1    3.872983
2    3.872983
dtype: float64

In [99]:
df.cumsum()

0   1   2
0   0   1   2
1   3   5   7
2   9  12  15
3  18  22  26

In [101]:
ser = pd.Series(np.random.randn(500))
ser[20:500] = np.nan
ser[10:20] = 5
ser.unique()

array([-2.24289724,  0.58835473, -0.58741495, -1.5345843 , -0.18567931,
        1.29721463,  0.12820453,  1.22675708, -1.93573942,  0.33265577,
        5.        ,         nan])

In [103]:
ser = pd.Series(np.random.randn(1000))
ser[::2] = np.nan
ser.describe(percentiles=[0.05,0.10,0.90])

count    500.000000
mean      -0.019229
std        0.997462
min       -2.864084
5%        -1.719589
10%       -1.315593
50%        0.004064
90%        1.204225
max        3.057198
dtype: float64

In [104]:
ser = pd.Series(['a','a','c','c','b',np.nan,'d','g'])
ser.describe

<bound method NDFrame.describe of 0      a
1      a
2      c
3      c
4      b
5    NaN
6      d
7      g
dtype: object>

In [109]:
df = pd.DataFrame({"x":['a','a','c','c','b'],"y":np.random.random(5)})
df.describe(include='all')

x         y
count     5  5.000000
unique    3       NaN
top       a       NaN
freq      2       NaN
mean    NaN  0.484598
std     NaN  0.305378
min     NaN  0.129166
25%     NaN  0.328869
50%     NaN  0.365439
75%     NaN  0.730515
max     NaN  0.869000

In [110]:
ser = pd.Series(np.random.randn(1000))
ser[::2] = np.nan
ser.min()

-2.5871709165336014

In [111]:
ser.max()

3.361537794463023

In [112]:
ser.idxmin()

47

In [113]:
ser.idxmax()

711

In [115]:
df = pd.DataFrame({'A':np.arange(-3,2),'B':np.ones(5)})
print(df)
df = df.transform({'A':np.abs,'B':lambda x : x+1})
print("==================")
print(df)

   A    B
0 -3  1.0
1 -2  1.0
2 -1  1.0
3  0  1.0
4  1  1.0
   A    B
0  3  2.0
1  2  2.0
2  1  2.0
3  0  2.0
4  1  2.0
