In [3]:
import numpy as np

In [8]:
arr = np.array([[[0,1,2,3],[4,5,6,7],[8,9,10,11]],
               [12,13,14,15],[16,17,18,19],[20,21,22,23]])

C:\Users\USER\AppData\Local\Temp/ipykernel_8748/2062062131.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([[[0,1,2,3],[4,5,6,7],[8,9,10,11]],


In [9]:
arr.ndim

1

In [10]:
arr.shape

(4,)

In [11]:
arr.size

4

In [12]:
arr.dtype

dtype('O')

In [13]:
arr.itemsize

8

In [14]:
arr.strides

(8,)

In [15]:
np.dtype(np.int16)

dtype('int16')

In [17]:
dt = np.dtype('>i4')
dt.name

'int32'

In [18]:
dt.byteorder

'>'

In [19]:
dt.itemsize

4

In [20]:
dt.type is np.int32

True

In [21]:
dt = np.dtype([('name',np.unicode_,16),('grades',np.float64,(2,))])
print(dt['name'])
print(dt['grades'])

<U16
('<f8', (2,))


In [22]:
arr = np.array([('jin',25,67),('suho',18,77)],
               dtype=[('name','U10'),('age','i4'),('weight','f4')])

In [23]:
arr

array([('jin', 25, 67.), ('suho', 18, 77.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [24]:
arr[1]

('suho', 18, 77.)

In [25]:
arr['age']

array([25, 18])

In [26]:
arr['age'] = 20
arr

array([('jin', 20, 67.), ('suho', 20, 77.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [27]:
arr['age'][1] = 20
arr['age'][0] = 32
arr

array([('jin', 32, 67.), ('suho', 20, 77.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [28]:
arr['weight'][0] = 80
arr

array([('jin', 32, 80.), ('suho', 20, 77.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [31]:
np.dtype([("",np.int16),("",np.float32)])

dtype([('f0', '<i2'), ('f1', '<f4')])

In [38]:
a = np.array([(1,2,3),(4,5,6)],dtype ='i8, f4, f8')
a[1] = (7,8,9)
a

array([(1, 2., 3.), (7, 8., 9.)],
      dtype=[('f0', '<i8'), ('f1', '<f4'), ('f2', '<f8')])

In [34]:
a = np.zeros(3, dtype=[('a', 'i8'), ('b', 'f4'), ('c,', 'S3')])
b = np.ones(3, dtype=[('x','f4'),('y','S3'),('z','O')])

In [35]:
b[:] = a

In [36]:
b

array([(0., b'0.0', b''), (0., b'0.0', b''), (0., b'0.0', b'')],
      dtype=[('x', '<f4'), ('y', 'S3'), ('z', 'O')])

In [37]:
a

array([(0, 0., b''), (0, 0., b''), (0, 0., b'')],
      dtype=[('a', '<i8'), ('b', '<f4'), ('c,', 'S3')])

In [39]:
arr = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
rows = np.array([[0,0],[3,3]],dtype = np.intp)
columns = np.array([[0,2],[0,2]], dtype = np.intp)
arr[rows,columns]

array([[ 0,  2],
       [ 9, 11]])

In [40]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [41]:
arr1= np.array([1, 2, 3, 4, 5])
arr2 = np.array([11, 12, 13])
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [42]:
arr1_nx = arr1[:,np.newaxis]
arr2_nx = arr2[:, np.newaxis]

In [43]:
arr1_nx

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [44]:
arr2_nx

array([[11],
       [12],
       [13]])

In [45]:
arr1_nx + arr2 #형태의 변화 5*3

array([[12, 13, 14],
       [13, 14, 15],
       [14, 15, 16],
       [15, 16, 17],
       [16, 17, 18]])

In [46]:
arr2_nx + arr1 # 3*5

array([[12, 13, 14, 15, 16],
       [13, 14, 15, 16, 17],
       [14, 15, 16, 17, 18]])

In [47]:
#numpy.transpose